---
- name: "upgrade packages."
  become: yes
  apt:
    upgrade: yes

- name: deploy backend
  become_user: ubuntu
  unarchive:
    src: ../../backend/artifact.tar.gz
    dest: ~/udapeople/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Running backend service
  become_user: ubuntu
  shell: |
    cd ~/udapeople/
    npm i    
    pm2 start npm -- run start
