---
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: " update dependancies"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    apt-get install -y nodejs  
    npm install --save glob
    
- name: "Copy backend build to server"
  become: yes
  unarchive:
    src:  ~/project/artifact.tar.gz
    dest: /home/ubuntu/
    owner: ubuntu

- name: "Copy package.json to server"
  become: yes
  copy:
    src: ~/project/backend/package.json
    dest: /home/ubuntu/
    owner: ubuntu
    
- name: Build backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm i
    # npm install
    sudo npm audit --audit-level=critical --force
    npm fund
    npm run build
   

- name: run backend 
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start --name backend npm -- start
    npm run start:prod
    pm2 ls